### PR TITLE
Constrains nan dependency

### PR DESCRIPTION
**Pull request by benbeltran**
Avoids installing nan 2.0.0 which breaks exiv2

### CODE REVIEW

**Comment by drewish** [comment]
Looks like that breaks the version of npm that ships with 0.8.x. Probably better to just get it updated for nan 2.0. I'll try to give that a look tonight.

**Comment by benbeltran** [comment]
Right, that makes sense. This is probably a dumb question, but the current state is broken on all versions of node ... And I don't see a version of nan supporting 0.8 newer than 1.3.0 ... Would using 1.x.0 be a better solution?

My concern is that this may be breaking production code that uses this library in all versions of node, not just 0.8. Either way, that fork works for anyone having that problem while support for 2.0 is added.

**Comment by benbeltran** [comment]
Updated to use 1.x.0, checked on Travis CI. This passes all tests. I guess it's a bit better than the original that used `^`

**Comment by drewish** [comment]
Awesome! Thank you!

**Pull request merged**
